### ISSUE TITLE
Copy Cat or real deal?

### ISSUE THREAD

**Issue by escoolioinglesias** [theonlyfoxy/CommanderGPT#3]
Hey, is this you and based on this repo ?

https://www.commandergpt.app/

I couldn't find information to corroborate that either on the README nor the website itself.

Thank you!

**Comment by theonlyfoxy** [comment]
Dear @escoolioinglesias,

Thank you for bringing this to my attention. However, I would like to clarify that the project you mentioned, "CommanderGPT" at https://www.commandergpt.app/, is not related to my project of the same name. The similarity in the project names is coincidental, and I have no affiliation with or knowledge of the project you mentioned.

If you have any questions or concerns regarding my project, please feel free to ask, and I'll be happy to provide you with any information you need.

Thank you,
Foxy
